import java.sql.Connection;

/**
 * A class representing an authentication token
 * <pre>
 *     <b>Domain</b>:
 *      token: String -- A unique authentication token generated by a random generator
 *      username: String -- Foreign key from User
 * </pre>
 */
public class AuthToken
{
    private String token;
    private String username;

    /**
     * Take an username and run a query in the database to find the authentication token, else create a new token
     * @param userID
     */
    public AuthToken(String userID)
    {
        //To be implemented later
    }

    /**
     * Take a token and query it in the database, setting this.username to the found username
     * @param tk
     * @param conn
     */
    public AuthToken(String tk, Connection conn)
    {
        //To be implemented later
    }

    public String getToken()
    {
        //To be implemented later
        return "";
    }

    public String getUsername()
    {
        //To be implemented later
        return "";
    }
}
